### ISSUE TITLE
Remaining Balance

### ISSUE THREAD

**Issue by Brock-Wood** [moontreeapp/moontree#100]
### Describe The User Story

As a User I want to know how many coins I have remaining when sending so that I can quickly see how many I will have left after my send transaction.

### Additional Context

When on the Send page, the users want to see not only how many coins they have and are sending, but what the remaining balance will be.

### Tasks For This Story

 - [x] #109
 - [x]  #110

### Design Spec ###
[Remaining Balance](https://xd.adobe.com/view/d21e350f-d5ab-49a2-a819-063268713714-874d/)

### Enhancement Of ###
[Specific Coin Holding](https://github.com/moontreeapp/moontree/issues/99)

**Comment by lastmeta** [comment]
I think this one currently exists, just have to format it to the new design

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [Coin Info](https://github.com/moontreeapp/moontree/issues/283)
