### ISSUE TITLE
Memo

### ISSUE THREAD

**Issue by Whale-Street** [moontreeapp/moontree#119]
### Describe The User Story

As a User I want a memo field on the send screen so that I can save a note (attach info) on the blockchain by including it in the transaction. 

### Additional Context

Note: A personal note that is saved locally to the device. 
Memo: Info that is included in a transaction (saved on the blockchain).

### Tasks For This Story

 - [x] #39
 - [x] #57

**Comment by Brock-Wood** [comment]
This is an Enhancement of the [Send Flow](#305)
