### ISSUE TITLE
[raven_front] Network Activity Indication

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#12]
### Describe The User Story

As a user I want to see when things are loading So that I know something is happening and I don't get confused. 

### Stories

 - [x] https://github.com/moontreeapp/raven_front/issues/41
 - [ ] https://github.com/moontreeapp/raven_front/issues/81
 - [x] https://github.com/moontreeapp/raven_front/issues/40

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [Loader](https://github.com/moontreeapp/moontree/issues/284)
