### ISSUE TITLE
Send Form

### ISSUE THREAD

**Issue by Brock-Wood** [moontreeapp/moontree#121]
### Describe The User Story

As a User I want an area that I can input the coin, amount, to, fee and personal note so that I can send coins/assets.

### Tasks For This Story

 - [x] #109
 - [x] #144

### Design Spec ###
[Send Form](https://xd.adobe.com/view/4941b0a6-2a86-450e-8dee-532588283c88-1c12/)

**Comment by lastmeta** [comment]
should we remove the secondary qrcode button here? it seems redundant
![image](https://user-images.githubusercontent.com/5642485/150605907-af4563a4-3b41-4e39-adb6-5d0afa8b6bf4.png)

**Comment by lastmeta** [comment]
it was decided to remove the top one, and only have the bottom one fill in the to.
