### ISSUE TITLE
User Level

### ISSUE THREAD

**Issue by Brock-Wood** [moontreeapp/moontree#131]
### Describe The New Page

As a power user I want the ability to change my user level so that I can perform advanced actions and not require steps to protect me.

### Stories For This Bucket

 - [ ] #

### Design Flow ###
[User Level](https://xd.adobe.com/view/08635fbf-1d03-48ad-8758-8af61fbf2345-5d30/)

**Comment by lastmeta** [comment]
Should this be an Advanced Settings page instead?

https://discord.com/channels/838841650331517021/839244697998590052/929159379759009802

"...we turn the User_Level page into a Advanced page with the options directly there..."
