### ISSUE TITLE
Security Wide Button

### ISSUE THREAD

**Issue by Brock-Wood** [moontreeapp/moontree#153]
### Describe The User Story

As a User I want a button to submit/change/set my password, pin, etc.

### Tasks For This Story

 - [ ] #

### Related ###

- [Wide Send Button](https://github.com/moontreeapp/moontree/issues/123)
- [Wide Share Button](https://github.com/moontreeapp/moontree/issues/138)

### Design Spec ###
[Security Wide Button](https://xd.adobe.com/view/5a361227-2aaa-44c3-8b9b-73c9d27f9606-0f65/)

**Comment by lastmeta** [comment]
fixed this at some point
