### ISSUE TITLE
[raven_front] Upgrade the send address field

### ISSUE THREAD

**Issue by corviato1** [moontreeapp/moontree#2]
Add the user ability to "send" RVN or assets to an Admin Asset or Unique Asset.
This would work by a user typing an asset name.  The app would then run the name and pull the address hash tied to the !Asset or #Asset.  It would then send to that hash.

It would also be cool if the transactions list would have a button to switch an asset name overlay for address hashes that are tied to a !Asset or #Asset

*Not sure if this needs to be button enabled, but that may be good for whatever edge case

**Comment by Brock-Wood** [comment]
#32 Covers this Suggestion.
