### ISSUE TITLE
Tell the user we're retrieving their funds

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#202]
### Describe The User Story

As a user I never want to see a blank holdings screen when I know I have holdings.

### Alternatives You've Considered

if we "remember" the balance from before a password change we can display that with a white scrim over it and a message that says, syncing with the network please wait. when the sync is complete the scrim is removed and in most cases the real produced balances will match the "remembered" balances and nothing would change on the screen but the scrim going away.

Or we could ignore the fact that we can remember past balances in one case and just have a blank screen that says "syncing with network, please wait" for either case.

### Additional Context

There are two contexts for when this is important - 
1. when they import an existing wallet that has never been in the app before. 
2. when they reset their password, reencrypt wallets and redownload historic data. 

in the first case the app has no way of knowing that they have a balance, in the second case the app can be made to remember previous balances.

I think we might could make an immediate call to electrum in the first case to very quickly find out if they have some kind of balance, even it we don't know exactly what assets those are yet.

In any event, we have to decide what we want the screen to look like when the user is awaiting electrum sync to finish.

### Tasks For This Story

 - [x] #206
 - [ ] #210

### Bugs For This Story

 - [ ] #

**Comment by Brock-Wood** [comment]
@lastmeta I think the best thing for now is to show the #116 on the front screen area, with text that informs the user what is going on. Eg. "Adding Imported Holdings" "Encrypting Your Holdings" etc.

We should probably set a minimum time that the loading screen is shown -- 3 sec minimum. That way we don't have a circumstance where the loader is briefly flashed on the screen.

Thoughts?

**Comment by lastmeta** [comment]
**Bottom line:** 
yeah that sounds great, I think I know the best thing to do: just send them back to the homepage and have the homepage display that, instead of having a separate loading screen after the behavior and then the homepage.

**My thought process:**
> that seems good, it means they basically see that screen twice. 
> 
> They click submit on their behavior (import or password change) and they get that screen right now anyway, then the snackbar comes up after "encryption has been finished" and they get sent back to the home page. The homepage will have no holdings to show (because it's redownloading them), so what you're suggesting is that the homepage have 3 states: 
> 1. nothing happening, and no holdings: "Your holdings will appear here"
> 2. something happening, and no holdings: "...ing your Holdings"
> 3. holdings available: view holdings
> 
> That sounds good? it basically means they'll see a very similar screen before and after the snackbar appears. If this is what we want, perhaps after they click we just send them back to the homepage immediately.

**Comment by Brock-Wood** [comment]
> That sounds good? it basically means they'll see a very similar screen before and after the snackbar appears. If this is what we want, perhaps after they click we just send them back to the homepage immediately.

Yes, exactly!

**Comment by lastmeta** [comment]
we have since moved away from https://github.com/moontreeapp/moontree/issues/206
