### ISSUE TITLE
[raven_front] Privacy Policy

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#23]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

**Describe the Feature You'd Like:**  
As a Lawyer
I want a privacy policy presented to users
So that they understand what information we collect

**Describe the Feature You'd Like:**
A place where users can read and understand what information we collect.

**Describe Feature Alternatives You've Considered:**
N/A

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [Legal User Agreement Documents](https://github.com/moontreeapp/moontree/issues/22)
