### ISSUE TITLE
Wallet Holdings - combine list items

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#233]
### Describe The User Story

As a user I want to see a clean list of items So that I can avoid the mental energy of associating main assets with their administrator tokens and the like.

### Alternatives You've Considered

The other option is to keep them as separate items, but show what type they are, but then you end up with different icons for the same asset, or the same icon repeated. probably not as ideal an option.

### Tasks For This Story

 - [x] #232

### Bugs For This Story

 - [ ] #

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [List](https://github.com/moontreeapp/moontree/issues/278)
