### ISSUE TITLE
[raven_front] User Agreement

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#24]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

**Describe the Feature You'd Like:**  
As a Lawyer
I want a user agreement presented to users
So that they can agree to using our wallet

As a Business Owner
I want a user agreement presented to users  
So that we mitigate business risk

**Describe the Feature You'd Like:**
A place where users can read and agree to using our mobile wallets.

**Describe Feature Alternatives You've Considered:**
N/A

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [Legal User Agreement Documents](https://github.com/moontreeapp/moontree/issues/22)
