### ISSUE TITLE
[raven_front] Risk Disclosures

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#25]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

**Describe the Feature You'd Like:**  
As a Lawyer
I want risk disclosures presented to users
So that they consent and are informed

As a Business Owner
I want risk disclosures presented to users  
So that we mitigate business risk

**Describe the Feature You'd Like:**
A place where users can read and agree (not sure if explicit agreement  is needed) to the risks of using our mobile wallets.

**Describe Feature Alternatives You've Considered:**
N/A

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [Legal User Agreement Documents](https://github.com/moontreeapp/moontree/issues/22)
