### ISSUE TITLE
dockerize electrum client

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#251]
### Describe The Task

We want to build and rebuild the electrum client in a docker image easily and efficiently.

**Comment by lastmeta** [comment]
https://github.com/Electrum-RVN-SIG/electrumx-ravencoin/blob/master/contrib/Dockerfile

**Comment by lastmeta** [comment]
make a docker compose file like this one to get it working on the droplet
https://github.com/lukechilds/docker-electrum-vertcoin/blob/master/docker-compose.yml

**Comment by lastmeta** [comment]
seems it might be easiest to add ravend into the dockerfile if we're unable to get the two talking over mapped ports, idk...

**Comment by kralverde** [comment]
https://github.com/moontreeapp/raven_server/blob/dev/Dockerfile
