### ISSUE TITLE
Backend Server

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#253]
### Describe The New Page

As a... user I want... things to go fast and be efficient
So I need a backend server to exist so all the computation and data management can be offloaded to it when appropriate.

Ultimately we need a load balancer, so we can spin up as many clones of the backend as we need to accommodate the load.

The server itself should take the load balancer pattern into account.

The server itself should be a dockerized image running the modified Electrum Client (or the existing electrum client with a moontree layer on top of it).

The moontree layer has a few goals: 
1. provide users their holding balances, transaction history, and any other information they require without the client needing to query each scrtiphash (address) each time it starts. 
2. We anticipate, the need for a pinning service, though this probably shouldn't be baked into the moontree layer, the moontree layer should serve as the connection to the pinning service much like it serves as the go between to the electrum server at least for bundled information.
3. aside from those things we will be charging users for certain actions and abilities, we'll need to have a database and management of that database to keep this kind of information as well.

### Stories For This Bucket

 - [ ] #252
 - [ ] #254

### Bugs For This Bucket

 - [ ] #

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by:
- #252 
- #254
