### ISSUE TITLE
[raven_front] Init Page Animation

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#28]
**Describe the Feature You'd Like:**
As a user I might be impressed by the liquid spinner we have in assets, but its choppy right now with the current design of how computation is handled.

**Describe the Feature You'd Like:**
I'd like the liquid spinner at least the first (few) time(s) I open the app - maybe not every time because it takes like 5 seconds. One solution, if we just want to see it once, the first time the app is ran, is to make it a part of a tutorial that runs the first time before anything at all happens. the only trick is that we'd have to save the flag that the tutorial ran as it's own file because it has to do the check before the database is loaded (which happens during the loading screen). I actually think this is probably the ideal solution.

**Additional Context:**
the current spinner that changes colors on the raven is more ideal as the choppiness doesn't matter as much.

**Created from**
https://github.com/moontreeapp/raven_front/issues/6

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [Splash Screen Flow](https://github.com/moontreeapp/moontree/issues/330)
