### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by Whale-Street** [moontreeapp/moontree#284]
### Describe The User Story

As a User I want a loading screen so that I know a desired action is being performed. 

### Additional Context

- Overlay
- Action Text ('creating,' 'sending,' etc.)
- Lottie Loading Animation (Tree grow, seed, regrow)

### Design Spec
[Loader Design Spec](https://www.figma.com/file/Lrcpz8wCHP9NcEHoIZciz5/Loader)

### Tasks For This Story

 - [ ] #

**Comment by Brock-Wood** [comment]
We are waiting for the animator to complete the lottie loader.

**Comment by Brock-Wood** [comment]
https://pub.dev/packages/lottie

We can use this package for implementing our loader and splash screen.

**Comment by Brock-Wood** [comment]
I have the lottie loader, I need to upload it to Figma and update this component.
