### ISSUE TITLE
[raven_front] Foreground Network Activity

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#29]
**Is your feature request related to a problem? Please describe.**
We have several "please wait" screens that show up for a second or a few seconds. they're functional but not pretty. 

**Describe the solution you'd like**
legit spinners. also we should look into how to reduce the wait times, but we should have some spinner anyway, so maybe that concern is a different ticket.

One has a "estimated wait time" maybe that should really have a countdown or something?  These are on sending (generating) a transaction, generating a new account (makes many hd wallets), and... I thought there was somewhere else too... idk. reconnecting perhaps? One place that doens't have it, but maybe should is when you've imported a wallet and it's downloading the transactions, all we have are those back ground indicators, but I think it might be best to have a snackbar saying, "downloading transactions in the background" so the app is still useable but the user knows its not synced

**Created from**
https://github.com/moontreeapp/raven_front/issues/6

**Tasks:**
- [ ] decide how you really want it to look

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [Loader](#284)
