### ISSUE TITLE
[raven_front] Loading Screen Hang

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#30]
**Prerequisites**
 - [x] Did you perform a cursory search?
 - [x] Are you running the latest version?

**Describe the bug**
The loading screen hangs on app startup.

**To Reproduce**
1. Run App
2. See error

**Expected behavior**
When the app loads it should show the loading screen and then the home screen.

**Screenshots**
https://user-images.githubusercontent.com/9276931/144446582-c4f15a09-097c-4701-9cf8-7ce145acfd14.mp4

**Smartphone (please complete the following information):**
 - Device: Note 20 Ultra
 - OS: Android

**Comment by lastmeta** [comment]
I haven't seen this on emulator since we switched away from datadog
