### ISSUE TITLE
Network Flow

### ISSUE THREAD

**Issue by Whale-Street** [moontreeapp/moontree#300]
### Describe The Suggestion

A flow where Users can change the server they are connected to.

#### Flow
- [Network Flow](https://www.figma.com/file/AzWqCuo0GRnCbvZ8yfTafG/Network-Flow)

#### Animation
- [Holdings -> Menu -> Settings](https://user-images.githubusercontent.com/9276931/162594146-acb32854-2285-40f9-b8c6-74a293bab921.mp4)
- [Settings -> Network](https://user-images.githubusercontent.com/9276931/162594458-7cf981d6-bf29-4714-84d4-d214c8a005c1.mp4)
- [Network -> Loading -> Snackbar](https://user-images.githubusercontent.com/9276931/162594728-96d39a68-5ff2-43ca-8ef2-d9a6fb9ed697.mp4)

- [x] #415

### Components
- #281 
- #279 
- #284 
- #277 
- #278 
- #276 
- #282 

- [x] #291
- [x] #353

**Comment by Brock-Wood** [comment]
This needs to be updated for [Security Flow](#311)
