### ISSUE TITLE
Watch Only Wallet

### ISSUE THREAD

**Issue by Whale-Street** [moontreeapp/moontree#303]
### Describe The Suggestion

As a User I want to keep track of my wallet holdings without keeping my private key in my Moontree wallet. 

### Additional Context

Wallets are made up of pub and priv keys. A user can choose to keep only their pub key, or only import a pub key, into their Moontree wallet. This allows the user to keep track of their holdings while eliminating the risks associated with storing their priv key.

**Comment by Brock-Wood** [comment]
This could be an enhancement to the [Export Flow](https://github.com/moontreeapp/moontree/issues/313). 

Upon export users would be presented with the option to Watch Only Export. The user would then be prompted with the [Backup Flow](https://github.com/moontreeapp/moontree/issues/335) verification. Once the user has proven they have created a backup of their 12 words, we would then delete their master priv key from the phone, while keeping their master pub key. 

Wallet Home -> Menu -> Import/Export -> Export -> Export Watch Only -> Backup Verification -> Wallet Home (Successful Watch Only Export Snackbar)
