### ISSUE TITLE
[raven_front] display memo data for transactions

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#31]
**Prerequisites**
 - [x] Did you perform a cursory search?
 - [x] Are you running the latest version?

**Is your feature request related to a problem? Please describe.**
transactions can have metadata (memos). should we show the ipfs stuff?

**Describe the solution you'd like**
add a tab to interpret and show memo on transaction page

**Created from**
https://github.com/moontreeapp/raven_front/issues/2

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [Memo](#119)
