### ISSUE TITLE
Message Flow

### ISSUE THREAD

**Issue by Whale-Street** [moontreeapp/moontree#318]
### Describe The Suggestion

A flow where users can send messages to the holders of their asset. 

### Additional Context

Messages do not require message channels. Message channels are meant to separate the types of messages that are sent to the holders of an asset. Users can 'subscribe' (ask for specific messages channel tokens) to receive only their messages.

Eg.
Main -> Any Message
Main~QTRREPORT -> Quarterly Report Messages
Main~DAILYPRICE -> Daily Price Messages

### Design Flow
[Message Flow](https://www.figma.com/file/ce2I4TcovaqiJ5O5C4TBsk/Message-Flow)

### Components
- #278 
- #282 
- #116 
- #281 
- #276 
- #279

**Comment by Brock-Wood** [comment]
My original understanding was that messages channels were required to send messages to holders. Because this is not the case, we need to figure out where else in the app messages can be initiated.
