### ISSUE TITLE
Splash Screen Flow

### ISSUE THREAD

**Issue by Whale-Street** [moontreeapp/moontree#330]
### Describe The Suggestion

A flow where users see a splash screen animation of the Moontree growing while the app initially loads.

### Additional Context

When the app first starts up, users should see a lottie file animation of the Moontree logo. This then should transition smoothly to the Wallet Home screen.

#### Flow
- [Splash Screen Flow](https://www.figma.com/file/0MxZ9ipNGXGODO0oeMWdIK/Splash-Screen-Flow?node-id=0%3A1)

#### Animation
- [Splash Screen -> Wallet Home](https://user-images.githubusercontent.com/9276931/164568414-9b5b3d6a-4644-4452-94bd-f7d74bacef5d.mp4)

### Tasks
- #389

**Comment by Brock-Wood** [comment]
Waiting for lottie files before creating flow. 

Designer is building the animation, but he has not completed it yet.

**Comment by Brock-Wood** [comment]
Received animations back, but they were not what we were looking for. The animator is creating new ones with updated guidance.
