### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by Whale-Street** [moontreeapp/moontree#333]
### Describe The Suggestion

As a designer I want to document where devs and designers can locate our placeholders so that they are easily accessed. 

### Design Spec
[Placeholders](https://www.figma.com/file/6d0SgGAOUFGDt80PF0E4sI/Placeholders)

- [x] #404
- [x] #405
- [x] #406

**Comment by Brock-Wood** [comment]
3 Areas with Placeholders:
- Wallet
  - Holdings (No Assets)
  - Coin Info (No Transactions)
- Manage
  - Holdings (No Manageable Assets)
  

The respective designs of these areas has been updated to reflect placeholder scenarios. 
 - #309 
 - #296

**Comment by lastmeta** [comment]
- [ ] #404
