### ISSUE TITLE
Create Asset Functionality

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#337]
### Describe The Task

creation ability (every type of asset, every permutation)

**Comment by lastmeta** [comment]
main asset 
https://rvnt.cryptoscope.io/tx/?txid=39233709050549287a0342524b493dbaf31f6b57a1e896b38ebf08ced799ac52

sub asset
https://rvnt.cryptoscope.io/tx/?txid=e042d89243e991fdd50b723bc481b3a9657c0f42df5f9f32b543cf92b83b5cfa

channel
https://rvnt.cryptoscope.io/tx/?txid=0f9a409666124cc9c57f924324f24e6180cc9e361f4b604d21b0cac1e5531160

**Comment by lastmeta** [comment]
https://rvnt.cryptoscope.io/tx/?txid=191839fbc7100e9992421cdc3337b98036d361540d17f584f60e2c15438f9699

**Comment by lastmeta** [comment]
Need to test reissue, Restricted assets and qualifiers and qualifier subs not implemented

**Comment by kralverde** [comment]
Full functionality for creating MAIN, SUB, UNIQUE, and MESSAGE CHANNELS.
