### ISSUE TITLE
[raven_front] Handle notes on transactions correctly

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#34]
**Prerequisites**
As a user I want to be able to save notes about a transaction

**Is your feature request related to a problem? Please describe.**
Notes can be added to transaction (memos are sent on the blockchain, notes could be saved on the device).
"note should be saved by transaction scripthash"
"note should be able to be saved in a reservoir (histories)"

**Additional context**
Notes are just on the device, so they will contain info for the sender, like, "for groceries". I think they might be handled correctly already but we should verify they are and that the design is ideal.

**Related to**
https://github.com/moontreeapp/raven_front/issues/22

**Created from**
https://github.com/moontreeapp/raven_front/issues/2

**Tasks:**
- [ ] figure out how we want to sync these notes across devices
- [ ] do we want to back them up?

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [Memo](#119)
