### ISSUE TITLE
[raven_front] Memos

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#35]
**Prerequisites**
as a user I want to save ipfs data in a transaction as a memo, I also want to view ipfs data from a transaction

**Is your feature request related to a problem? Please describe.**
Memos can be added to transaction (memos are sent on the blockchain, notes could be saved on the device).
"memo detected and captured upon creation of History object..."
"memo should be saved by transaction scripthash (transaction Memo should be saved in the database #5)"
"memo should be able to be saved in a reservoir (histories)"

**Additional context**
When it comes to assets I think we handle the 'memo' correctly because they're usually IPFS hashes and we save those as 'metadata' objects. But when it comes to regular old transactions - I don't know if we capture the 'memo' or 'metadata' at all, let alone handle it correctly. Furthermore, do we even have to? Should we show that info or just leave it up to the block explorers to do that?

**Created from**
https://github.com/moontreeapp/raven_front/issues/2

**Tasks:**
- [ ] https://github.com/moontreeapp/raven_front/issues/33
- [x] https://github.com/moontreeapp/raven_front/issues/5

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [Memo](#119)
