### ISSUE TITLE
[raven_front] transaction Memo should be saved in the database

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#39]
// how do we detect metadata?
    /*Tron — Yesterday at 6:51 PM
      You can add messages to transactions by putting the IPFS hash of the message in the OP_RETURN.
      They're called memos. They will be public.*/

meta stack — Today at 9:55 AM
one last question for ya, I was told that regular transactions have an OP_RETURN field that can be used to define a "Memo" (like an ipfs hash) on regular transactions. If this is true, is that memo field available to us through an endpoint? if not, no problem, but if it is I'll capture it (edited)

kralverde — Today at 9:56 AM
OP_RETURN is an output of a transaction
In the actual bytes it goes OP_RETURN (op push) text in lieu of the script (and a sat value of 0) (edited)
In bitcoin the message must be max 40, in rvn i think its 80
Is that what you were asking?

meta stack — Today at 9:59 AM
well, that's good info, but I'm more asking about how to detect/get at it

kralverde — Today at 9:59 AM
Youd need to get the transaction itself

meta stack — Today at 10:00 AM
I have a note on my todo list that I wrote a long time ago that says "memo should be saved in the database" you mean in the txHash?

kralverde — Today at 10:00 AM
No
Its not saved youll need to get the actual transaction
And parse it

meta stack — Today at 10:01 AM
with transaction.get?

kralverde — Today at 10:01 AM
(Which should be done for verification anyway since scripthash can have collisions)
Yeah

meta stack — Today at 10:02 AM
do you know which field in the verbose version I'd have to parse? 
https://electrumx-ravencoin.readthedocs.io/en/latest/protocol-methods.html#blockchain-transaction-get (edited)

kralverde — Today at 10:02 AM
The vout
OP_RETURN should be the last, but its not required
And you can just grab the idx’th value to verify the address for normal transactions (edited)

meta stack — Today at 10:03 AM
cool thanks!

kralverde — Today at 10:06 AM
Heres an example of a tx with opreturn https://rvn.cryptoscope.io/api/getrawtransaction/?txid=32741ab4d06535368ecf835ecde97fd1d9b9ec68fd028a0aa1440b8c430a8e2f&decode=1

**Comment by lastmeta** [comment]
see #352
