### ISSUE TITLE
optimize download view

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#397]
### Describe The Suggestion

having fixed the download process to derive 20 at a time (#394) we have a better idea of whats possible for optimization.

ok, to get a list of assets and balances we own we should be able to call the aggregate endpoint on the electrum server. that's fast.

to get a list of transactions we've been involved with we can call getHistories on every address in our wallet, pretty fast.

I bet we should probably get the UTXOs from the server too by calling the UTXO endpoint instead of building them ourselves. that would be faster, as in you could send before we even downloaded all the transactions, nearly right away.

it's only the details of those assets that take some time to get. if we make the loading UI placeholders for the In/Out indicator and the aggregate amount on the list then we can show that while they're downloading.

perhaps these steps are post MVP but it would be a massive improvement to user experience.

### Additional Context

this was brainstormed in https://github.com/moontreeapp/moontree/issues/347#issuecomment-1072067610

**Comment by Brock-Wood** [comment]
I assume this also means that for MVP UI/UX, we'll want to disable the send button until the UTXOs are known and built. I'll make note of this in #309.
