### ISSUE TITLE
Receive screen not populated

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#428]
### Describe The Task

if you're on an asset and you press receive it doesn't autopopulate the asset as the one you want specifically.

### Additional Context

send screen autopopulates. should we have the receive button on the "transactions" screen if it is not custom to that asset?

**Comment by lastmeta** [comment]
@Brock-Wood should it?

**Comment by Brock-Wood** [comment]
> @Brock-Wood should it?

Yes
