### ISSUE TITLE
[raven_back] client null on startup

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#43]
### Describe The Bug

we try to add an address using the client too early - before a client exists.

### To Reproduce

![image](https://user-images.githubusercontent.com/5642485/146038628-867b0a55-7d2c-4606-a512-160160c8199a.png)

### Expected Behavior

this function shouldn't be triggered until after the client is setup. it should wait in the stream

### Additional Context

doesn't cause any other issues

### Tasks For This Bug

 - [ ] https://github.com/moontreeapp/raven_front/issues/???

**Comment by lastmeta** [comment]
yes, there was something wrong with this quick fix, it doesn't replay all items added to the stream, just the latest, so we need to use some other pattern, probably the backlog pattern until we find a more generalized stream solution

**Comment by lastmeta** [comment]
implemented backlog pattern in https://github.com/moontreeapp/moontree/tree/62c637d8eac9675975a811cdde27f40cddf4bd18
