### ISSUE TITLE
Send error on device

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#443]
### Describe The Bug

on the emulator I can't recreate this issue, but on device I see it.

when trying to send I get an error about vouts not being present. I'm wondering if on device transaction download process never completes and thats why the transaction list never shows up... maybe both issues are caused by this.

anyway see image to see that the vout is missing, indicating transactions didn't complete downloading

### To Reproduce

test send on device

### Expected Behavior

calculates total - succsfully gathers utsxo

### Screenshots

![image](https://user-images.githubusercontent.com/5642485/163854735-45925549-64a8-4d0b-ad86-78ea8b1ad6ee.png)

### Tasks For This Bug

 - [ ] #

**Comment by lastmeta** [comment]
kral is working on this by collecting the ScripthashUnspent object directly rather than looking up it's Vout, because if the vout isn't downloaded yet we get this error.

**Comment by kralverde** [comment]
Solved by prioritizing downloading transactions pertaining to the calculated vouts rather than waiting for them to happen as history downloads
