### ISSUE TITLE
ignore allow message crashes app

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#453]
### Describe The Bug

got this error when we ignored the "allow" message
![image](https://user-images.githubusercontent.com/5642485/163837851-d92efab0-9859-4e4c-93b1-d4d7307c48f5.png)

### To Reproduce

feedback -> upload ignore message

### Expected Behavior

just goes back to feedback page.

### Tasks For This Bug

 - [ ] #

**Comment by Whale-Street** [comment]
On Android, asking for file permissions works fine now.

On iOS we do not ask for file permissions or directory access.

See #503 for camera access bug.
