### ISSUE TITLE
Section Flow

### ISSUE THREAD

**Issue by Whale-Street** [moontreeapp/moontree#461]
### Describe The Suggestion

As a User I want to navigate between the three app sections (wallet, manage, swap).

### Additional Context

The #282 Component gives user the ability to navigate between the primary section of the app. This issue is meant to document this flow and its animations.

#### Flow
- [Section Flow](https://www.figma.com/file/9vkBolmGW6wAEuGP7zgu7D/Section-Flow?node-id=2%3A12309)

#### Animation
- [Section Animation](https://user-images.githubusercontent.com/9276931/164339231-375ec07d-64aa-4a71-b24c-08fbf125f2b5.mp4)

**Comment by lastmeta** [comment]
what do you think about section to section changes leaving the app bar static instead of fading it in as well? it's contents could fade in/change with the section change
