### ISSUE TITLE
Security Triggers

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#48]
### Describe The Solution
We don't force people to use a password, and we don't even mention it up front. but we should somehow encourage security.

### Additional Context
Lets make triggers for when to implement greater and greater security. we must keep track of if these triggers have been displayed, so as to not pop up again and again. perhaps when they get some balance above 0 rvn we suggest they set a password or biometrics or pin or something, then when its higher we suggest they export what they don't need to cold storage and only keep what they need to use on the device.

### Enhances
[Security Flow](https://github.com/moontreeapp/moontree/issues/311)
[Backup Flow](https://github.com/moontreeapp/moontree/issues/335)
[Watch Only Wallets](https://github.com/moontreeapp/moontree/issues/303)

- [x] #421
- [x] #420

**Comment by lastmeta** [comment]
logic: if anything prompt for backup
when: before holding on startup - before primary action, before section change -
