### ISSUE TITLE
sending asset to self results in higher balance

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#493]
### Describe The Bug

we had 1,00,003 MOONTREE and I sent one to ourself to test sending, and then it said we had 1,000,004 MOONTREE, so I reconnected to clear the cache and it went back down to 1,00,003

### To Reproduce

send to self

### Expected Behavior

seems to work fine with RVN

### Additional Context

I don't remember seeing this issue recently so I think it may have been introduced earlier today

**Comment by kralverde** [comment]
ACK
