### ISSUE TITLE
tab bar not perfect on all aspect ratios

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#506]
### Describe The Bug

looks perfect on my android, but not on emulator

### To Reproduce

transactions screen

### Expected Behavior

2px

### Screenshots

![image](https://user-images.githubusercontent.com/5642485/165811512-bfd2028a-4960-457e-a7ae-488de0ea3c5f.png)

### Tasks For This Bug

 - [ ] #

**Comment by lastmeta** [comment]
nearly attached it to the front and looks pretty cool, but the blur blurs out the entire coinspec so I don't think this solution will work
![image](https://user-images.githubusercontent.com/5642485/166300137-fdf59757-adb8-4bf5-b61b-e3fbdaf01906.png)

**Comment by lastmeta** [comment]
This is really two bugs: the bar is not 2 pixels on some aspect ratios, and when you bring up the os bottom nav it hides the bar completely.

I believe both are fixed by putting the tab bar on the front, but That's a change to the design as it moves up with the list.

**Comment by Whale-Street** [comment]
@lastmeta I think the best fix is to have the tabs scroll up with the list, and then have them hide behind the appbar when the front layer is at full height.
![Screen Shot 2022-05-04 at 11 03 43](https://user-images.githubusercontent.com/9276931/166740874-fe7782ae-b6c0-41ea-9807-ce2469c3d8e1.png)
