### ISSUE TITLE
Incorrect History Ordering

### ISSUE THREAD

**Issue by Whale-Street** [moontreeapp/moontree#534]
### Describe The Bug

When sending two subsequent transactions, the first transaction is being displayed second and the second first.

### To Reproduce

Send a transaction, then send another.
While the transactions are still in the mempool, observe them in a coin's transaction history. 

### Expected Behavior

They should be in the correct order by time sent.

### Screenshots

![Screenshot_20220504-101753_Squid](https://user-images.githubusercontent.com/9276931/166734433-c67960e4-2afc-42cc-b222-56d331566a64.jpg)

### Tasks For This Bug

 - [ ] #

**Comment by lastmeta** [comment]
I think we order transactions by height, but maybe we have to order mempool transactions by time or something

**Comment by kralverde** [comment]
unfortunately mempool transactions aren't really "ordered" in any way, but we can maintain the state of what we currently think is in the mempool and add/remove from that to keep an order
