### ISSUE TITLE
[ravencoin_wallet] Support Asset Transfer

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#56]
**Is your feature request related to a problem? Please describe.**
Must support creation of transactions to send RVN native assets of all kinds

**Describe the solution you'd like**
as far as the API goes, I want `ravencoin.TransactionBuilder` to support sending assets instead of RVN perhaps through 
`txb.addAssetOutput(toAddress, asset, amount);`

as requested in 
https://github.com/moontreeapp/raven_back/issues/31

**Comment by Brock-Wood** [comment]
@lastmeta I assume this can be deprecated and closed?

**Comment by lastmeta** [comment]
> @lastmeta I assume this can be deprecated and closed?
> 

@Brock-Wood oh yes
