### ISSUE TITLE
api skeleton

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#566]
### Describe The Suggestion

new design - client is light, server heavy lifting - extremely react. 

Wallet:
api: only get the data you need (by screen)
tbc

### Additional Context

eventually we'll implement smart caching, but for mvp lets not consider it, unless there's a situation that obviously effect the api simply.

**Comment by lastmeta** [comment]
we may want to look into graphql when designing the api https://graphql.org/learn/

**Comment by Whale-Street** [comment]
This is going to be much more complex than anticipated -- which is fine but will require more discussion and research before implementing. 

Ideally Moontree (we) should create new RIP standard proposals before designing the Moontree server API. 

We'll want to discuss and look further into:
- https://eips.ethereum.org/EIPS/eip-1193
- https://eips.ethereum.org/EIPS/eip-695
- https://eips.ethereum.org/EIPS/eip-155
- https://eips.ethereum.org/EIPS/eip-2255
- https://eips.ethereum.org/EIPS/eip-1474
