### ISSUE TITLE
Add Transaction Type to History

### ISSUE THREAD

**Issue by Whale-Street** [moontreeapp/moontree#567]
### Describe The Suggestion

As a User I want to know the type of a transaction when browsing my transaction history. 

This is an enhancement of the [List Component](https://github.com/moontreeapp/moontree/issues/278)

### Additional Context

![Screen Shot 2022-05-10 at 10 15 35](https://user-images.githubusercontent.com/9276931/167675591-eb97c6f6-154e-4bc7-a601-933f2f6bd799.png)
![Screen Shot 2022-05-10 at 10 19 39](https://user-images.githubusercontent.com/9276931/167675868-8e282e73-2bf6-4008-b606-ebb6d2cb6e77.png)

**Comment by lastmeta** [comment]
done
