### ISSUE TITLE
[ravencoin_wallet] Add optional memo as part of a transaction

### ISSUE THREAD

**Issue by canadaduane** [moontreeapp/moontree#57]
"In a vout, the amount is 0 and the locking script hash is OP_RETURN OP_PUSH {1-40 bytes of data}. For rvn i believe its 1-80 actually"

https://bitcoin.stackexchange.com/questions/29554/explanation-of-what-an-op-return-transaction-looks-like

**Comment by lastmeta** [comment]
see #352
