### ISSUE TITLE
iphone ui bugs

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#572]
### Describe The Bug

1. keyboard on create page no mic - I think mic default doesn't come up automatically on obscure text
2. keyboard "done" button might should be something else "unlock" "return" or something.

**Comment by Whale-Street** [comment]
- ![Should not Scroll video](https://user-images.githubusercontent.com/9276931/168130617-9382e5b0-c30f-4e10-88a7-0fe5212e5994.mp4)
- ![20220512_104001](https://user-images.githubusercontent.com/9276931/168130649-0f080a2c-1240-4236-a4df-28b5273b5603.jpg)
- ![20220512_104030](https://user-images.githubusercontent.com/9276931/168130675-b0f9cb0f-4b2c-4d1a-af49-fdfc21ee8e80.jpg)
- ![20220512_104131](https://user-images.githubusercontent.com/9276931/168130686-c2568922-697a-4657-9bb0-d1c56c5a4d00.jpg)
