### ISSUE TITLE
Receive Screen Bugs

### ISSUE THREAD

**Issue by Whale-Street** [moontreeapp/moontree#576]
### Describe The Bug

No logo on the QR code and the contents of the screen scroll.

### To Reproduce

Navigate to the Receive screen.

### Expected Behavior

The qr code should have a Moontree logo and the contents of the screen should not scroll.

### Screenshots

![Screenshot_20220512-111439](https://user-images.githubusercontent.com/9276931/168132520-34e9161d-eb41-4a17-956e-eea7920b2d4d.jpg)

https://user-images.githubusercontent.com/9276931/168132548-c34673fc-f35a-41a4-9ecb-d1923e93e98d.mp4

### Tasks For This Bug

 - [ ] #

**Comment by Whale-Street** [comment]
The logo was causing an issue with scanning the qr code in #503. It was removed to fix that issue. 

If we want to have a logo, we'll probably need to use a different scan/qr lib.

**Comment by lastmeta** [comment]
must fix the scrolling issue

**Comment by Whale-Street** [comment]
The solution that was implemented did not take into account the navbar being raised as a result of the system navbar being displayed. This needs to be taken into account.
