### ISSUE TITLE
Import Space Bug

### ISSUE THREAD

**Issue by Whale-Street** [moontreeapp/moontree#578]
### Describe The Bug

When importing, if there is an extra space at the beginning of the textfield, the app thinks that you are wanting to import an encrypted key, wif, etc..

### To Reproduce

- Settings
- Import/Export
- Import
- Tap text field
- Add space to the beginning
- Input seed (correctly recognized as pneumonic)
- Tap import 

### Expected Behavior

The textfield should accurately recognize encrypted seeds from non-encrypted correctly. This may be as simple as stripping the first char if it is a space. 

### Screenshots

![Screenshot_20220512-121233](https://user-images.githubusercontent.com/9276931/168142266-02bb0755-b3d2-4bbb-9ae3-c83dcff2f479.jpg)
![Screenshot_20220512-121238](https://user-images.githubusercontent.com/9276931/168142391-0609b867-d2e3-4fd2-bfbe-2f27926cb36d.jpg)

### Tasks For This Bug

 - [ ] #

**Comment by lastmeta** [comment]
Also on import screen: can't talk your words into it - one at a time. this was due to the input formatter, removed and now we wait until user is done to make text lowercase.

**Comment by Whale-Street** [comment]
this bug is also present if there is an extra space at the end, as opposed to the beginning.
