### ISSUE TITLE
Upgrade to Isolates

### ISSUE THREAD

**Issue by Whale-Street** [moontreeapp/moontree#581]
### Describe The Suggestion

We may be able to spawn individual threads (dart/isolates) when processing requests and handling different tasks.

### Additional Context

We could add isolates when grabbing and processing data. This would allow our animations to not stutter and lag. We would not have to show an animation first, and let it run smoothly, before starting a heavy process. 

Current:
- Do Something -> Some Animation -> Start Process

Desired:
- Do Something -> (Some Animation, Start Process)

**Comment by lastmeta** [comment]
https://itnext.io/minimalist-guide-to-isolates-in-dart-flutter-dd5bdee031e
