### ISSUE TITLE
Send Form Not Scrolling

### ISSUE THREAD

**Issue by Whale-Street** [moontreeapp/moontree#586]
### Describe The Bug

On the send page, the text fields should be scrollable on screens that are not able to display the entire form. Currently the form is not scrolling and hides the note text field. 

### To Reproduce

- Start App
- Tap Send Button
- Observe Send Form

### Expected Behavior

The form should scroll when not all fields are displayed.

### Tasks For This Bug

 - [ ] #

**Comment by lastmeta** [comment]
#588
