### ISSUE TITLE
Incorrect Holdings Quantity

### ISSUE THREAD

**Issue by Whale-Street** [moontreeapp/moontree#625]
### Describe The Bug

Incorrect amount after sending... had 50 asset, sent 5, then it showed I had 95, lol. Restarted and it corrected itself to show 45.

### To Reproduce

Pick an asset, send subset of quantity, potentially observe the incorrect amount held.

### Expected Behavior

Show the correct amount held.

### Additional Context

mainnet

### Screenshots

![Screenshot_20220525-175124](https://user-images.githubusercontent.com/9276931/170388374-0c6d6e79-ed3f-4575-9c8d-96e1249affb1.jpg)

**Comment by lastmeta** [comment]
tried to duplicate this on testnet (using a brand new wallet), and unable to duplicate.

**Comment by lastmeta** [comment]
we've seen both too much and too little:
50 - 5 -> 95
35 -5 -> 20
so it seems it is downloading the incorrect unspents, or its a race condition, where it's building a balance from the unspents before they are all downloaded.

most recently, this remained a problem even after restarting the app.

**Comment by Whale-Street** [comment]
After testing further we discovered this is most likely a race condition with the change, utxos and updating.
