### ISSUE TITLE
Add Icons to Nav Bar

### ISSUE THREAD

**Issue by Brock-Wood** [moontreeapp/moontree#84]
### Describe The Task

- [ ] #83 
- [ ] #82 
- [ ] #81 
- [ ] #80 

make them links that send the user to their corresponding pages (details of those pages in their other stories)

### Additional Context

[Nav Bar](https://github.com/moontreeapp/moontree/issues/79)

**Comment by lastmeta** [comment]
this is not closed because we need to make the buttons links to the other pages still

**Comment by lastmeta** [comment]
button spacing - sizes are incorrect revisit.

**Comment by lastmeta** [comment]
see if manage has been combined to create

**Comment by lastmeta** [comment]
links look good, but are not very functional, wont be until we fix the routing so that each acts as it's own sub app and essentially has it's own isolated routes/ history. this means we'll probably have to move away from using named routes and research views in navigation.

**Comment by lastmeta** [comment]
closing I'll make a new ticket for researching better routes.
