### ISSUE TITLE
Make Holding List Item Template

### ISSUE THREAD

**Issue by Brock-Wood** [moontreeapp/moontree#85]
### Describe The Task

we need each item in the holding list to show the amount and the name of the asset, along with an arrow to indicate it's the top of something larger.

### Additional Context

[Holdings](https://github.com/moontreeapp/moontree/issues/78)

**Comment by lastmeta** [comment]
Also, on the home page what should it display if they have no holdings,  "this is where your holdings will show up?" or should it show a RVN 0? In our case we cannot connect, and we don't have info in the database, so even though we have an address with a balance we can't see the balance, what should we see instead?
