### ISSUE TITLE
Show App Connection/Status in Backdrop Back Layer

### ISSUE THREAD

**Issue by Brock-Wood** [moontreeapp/moontree#89]
### Describe The Task

As a user I want to see the status of my connection to the 'rvn' network (really the electrum network, but its all the same to the user).

It should have the following speicficaitons:

it should serve as a busy-signal hint too. So when actively communicating with the network (or even when doing some internal computation to the app that takes any significant amount of time) it should circle around to indicate the app is busy or waiting for something.

Perhaps you could tap it to get a message about what it's busy doing, but that's not entirely necessary as it should be pretty obvious by context and the forthcoming snackbar message.

### Additional Context

[Backdrop](https://github.com/moontreeapp/moontree/issues/77)

**Comment by lastmeta** [comment]
Just need to animate it using a gif or something, the correct way, it already gets the right triggers to run etc.

**Comment by lastmeta** [comment]
in order to proceed we need the animation, and plug it into the existing transformations, and we need to fix the issue where it's red even when its connected.

**Comment by lastmeta** [comment]
show green if connected, show red if not. We'll deal with the animation later.

**Comment by lastmeta** [comment]
awaiting a spinning white circle animation, one that comes out from center, spins one rotation and then goes back to center.

**Comment by lastmeta** [comment]
colors are fixed, we'll make the animation an enhancement if we want to do it later
