### ISSUE TITLE
Nav Drawer

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#94]
### Describe The User Story

As a user I want to see primary destinations when I open the left drawer so that I can get to places that are useful but on immediately linked on the home page.

### Tasks For This Story

 - [x] https://github.com/moontreeapp/moontree/issues/95
 - [x] #207

### Design Spec ###
[Nav Drawer](https://xd.adobe.com/view/3dba2c8d-6bd9-407c-9950-07d9360f56ae-68e9/)

**Comment by lastmeta** [comment]
Enhancement 1 - bring down the front layer almost all the way, and traversal menu items are now on the back page instead of front. see spec.

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [Nav Drawer](https://github.com/moontreeapp/moontree/issues/280)
