### ISSUE TITLE
Conform existing nav bar to new design

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#95]
### Describe The Task

see link in story

**Comment by lastmeta** [comment]
1. what should the header look like if there are multple accounts?
2. do you want this drawer to pull out a certain number of pixels or a certain percentage of the screen?
3. can you add the assets (moontree logos) to the project?
4. what is the icon called for import/export? I can only find the wallet without the plus symbol

**Comment by Brock-Wood** [comment]
Nav drawer is not ready yet...

**Comment by lastmeta** [comment]
if the nav drawer is open it is just a container with a blue background. We also need to apply a white scrim to the front layer including navbar with a guesture dector to hide the nav drawer.

hiding and showing the drawer should be accoplished by adding a value to the stream. the button passes true if drawer is not viewable, false if it is, scrim is always false. on page load (outer page like holdings page) we should pass false to the stream in init. the container of the nav drawer should be a widget that is the stream, and rebuilds upon seeing the toggle.
