### ISSUE TITLE
Specific Coin Holding

### ISSUE THREAD

**Issue by Brock-Wood** [moontreeapp/moontree#99]
### Describe The User Story

As a User I want to see the amount of a specific coin that I'm holding so that I know the amount and how much it is worth.

### Additional Context

When a user clicks on a specific coin that they are holding, they are taken to the Wallet Coin page. On the wallet coin page it would be nice to show the user the logo, the amount and how much the amount is worth is USD.

### Tasks For This Story

 - [ ] #

### Design Spec ###
[Specific Coin Holding](https://xd.adobe.com/view/21df763f-78f7-45ce-8531-0a316659e943-748c/)

**Comment by lastmeta** [comment]
made the balance header during Send page building

**Comment by Brock-Wood** [comment]
This has been deprecated and replaced by [Coin Info](https://github.com/moontreeapp/moontree/issues/283)
